# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "ibank-terraform-state"
    dynamodb_table = "ibank-terraform-locks"
    encrypt        = true
    key            = "global/terraform.tfstate"
    region         = "us-east-1"
  }
}
